### ISSUE TITLE
Console output stderr and stdout

### ISSUE THREAD

**Issue by genofire** [bdlm/log#16]
Hi,
i am thinking about, why is everything prompt to `stderr`, debug (and info) messages should be at `stdout`.

Now i am thinking of how to split them easiest with a `hooks`, still make it possible to disable low level messages. (and keep it simple across multiple packages)

Any Idea or suggestion ?

**Comment by mkenney** [comment]
Hi @genofire, thanks for opening an issue.

Yes, `stderr` is just the default but you can specify the output to be anything you want including files and network adapters (any `io.Writer`). There are two ways, 

1. if you're using the package-level exported logger you can set the default output with `log.SetOutput(os.Stdout)`
1. if you're using your own logger instance you can update it directly:
   ```go
   logger := log.New()
   logger.Out = os.Stdout
   ```

**Comment by genofire** [comment]
I like the version 1, but errors, panics and fatal should still be on `stderr`.

**Comment by mkenney** [comment]
Oh, I see, I misunderstood. I think a hook _is_ what you need.

I think you could just do something simple like this:
```go
import (
	"os"

	"github.com/bdlm/log"
	stdLogger "github.com/bdlm/std/logger"
)

type Hook struct{}

func (hook *Hook) Fire(entry *log.Entry) error {
	switch entry.Level {
	case log.PanicLevel:
		entry.Logger.Out = os.Stderr
	case log.FatalLevel:
		entry.Logger.Out = os.Stderr
	case log.ErrorLevel:
		entry.Logger.Out = os.Stderr
	case log.WarnLevel:
		entry.Logger.Out = os.Stdout
	case log.InfoLevel:
		entry.Logger.Out = os.Stdout
	case log.DebugLevel:
		entry.Logger.Out = os.Stdout
	default:
	}

	return nil
}

func (hook *Hook) Levels() []stdLogger.Level {
	return log.AllLevels
}
```
and just add it in your main
```go
func main() {
	log.AddHook(&Hook{})
}
```

_updated based on feedback below_

**Comment by mkenney** [comment]
I'm going to take that to mean your issue is solved 😃 

Feel free to re-open this if you have more trouble.

**Comment by mkenney** [comment]
There is a little bit in the wiki, this page touches on this point: https://github.com/bdlm/log/wiki/Multiple-outputs

But I agree, I'll add a link to this conversation in the wiki.
